services:
 questionnaire-fce-fhir-converter:
    image: bedasoftware/questionnaire-fce-fhir-converter:latest
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      timeout: 30s
      retries: 50
 watch-seeds-init:
    image: bedasoftware/fhirsnake:latest
    command:
      - watch
      - --external-fhir-server-url
      - ${FHIR_SERVER}
      - --external-questionnaire-fce-fhir-converter-url
      - http://questionnaire-fce-fhir-converter:3000/to-fhir
    volumes:
      - .:/app/resources

